# Generated by Django 6.1.1 on 2026-09-03 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Not yet confident"),
                            (2, "Developing"),
                            (3, "Solid enough to practice"),
                            (4, "Confident"),
                            (5, "Could teach it"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "recall_response",
                    models.TextField(max_length=2000),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="curriculum.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ConceptNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_note",
                        to="curriculum.concept",
                    ),
                ),
            ],
        ),
    ]
