
"""Maintainable original curriculum manifest for the full DSA roadmap.

Source rationale and limitations are documented in docs/ROADMAP_CONTENT.md.
"""

def _lesson(*, name, slug, order, summary, intuition, explanation, example,
            complexity, guidance, traps, practice, checkpoint, prerequisites=()):
    return {
        "name": name, "slug": slug, "order": order, "summary": summary,
        "intuition": intuition, "explanation": explanation,
        "examples": [example], "complexity_notes": complexity,
        "implementation_guidance": guidance, "common_traps": traps,
        "guided_practice": practice, "checkpoint": checkpoint,
        "prerequisite_slugs": list(prerequisites),
    }

def _topic(*, name, slug, display_order, description, concepts):
    return {"name": name, "slug": slug, "display_order": display_order,
            "description": description, "concepts": concepts}

ROADMAP_TOPICS = [
_topic(
    name="Algorithmic Foundations", slug="algorithmic-foundations", display_order=1,
    description="Build programming, modeling, correctness, and cost-model habits.",
    concepts=[
        _lesson(name="Problem Solving and Cost Models", slug="problem-solving-and-cost-models", order=1,
            summary="Translate prompts into inputs, outputs, constraints, and a measurable plan.",
            intuition="A problem is a contract: input space, output predicate, and resource budget.",
            explanation="Restate the contract, make a tiny example, estimate the largest input, and compare brute force with a scalable plan before coding.",
            example={"title":"Duplicate detection","input":"[4,7,2,7]","output":"True","walkthrough":"A seen set trades memory for one linear scan.","code":"seen = set()\nfor value in nums:\n    if value in seen: return True\n    seen.add(value)"},
            complexity="Name time and extra space; distinguish worst-case, expected, amortized, and pseudo-polynomial claims.",
            guidance="Write contract, constraints, brute force, bottleneck, improved idea, invariant, and complexity before implementation.",
            traps="Coding before clarifying output, ignoring constraints, and claiming optimality without assumptions.",
            practice="For pair sum, propose brute force and hash-based plans and predict which survives n=100000.",
            checkpoint="Can you state the contract, dominant loop, and time/space complexity?",
        ),
        _lesson(name="Python for DSA", slug="python-for-dsa", order=2,
            summary="Use sequences, dictionaries, sets, functions, and mutation deliberately.",
            intuition="Python is high-level notation over concrete operations; fluency includes knowing cost and mutation.",
            explanation="Practice indexing versus values, list growth, lookup, slicing, functions, and aliasing with standard-library tools.",
            example={"title":"Values and indices","input":"nums=[10,20,30]","output":"[(0,10),(1,20),(2,30)]","walkthrough":"enumerate gives index and value; range(len(nums)) gives indices.","code":"for index, value in enumerate(nums): print(index, value)"},
            complexity="Indexing is typically O(1), list membership O(n), expected dict/set membership O(1), and slicing copies.",
            guidance="Use enumerate for pairs, append to grow, and nums[:] for an explicit shallow copy.",
            traps="Confusing values with indices, enumerate(len(nums)), and assuming nums2=nums copies.",
            practice="Predict aliasing for nums2=nums and nums3=nums[:], then mutate each.",
            checkpoint="When do you need a value, index, or both, and what does the operation cost?",
            prerequisites=("problem-solving-and-cost-models",),
        ),
        _lesson(name="Complexity and Asymptotic Analysis", slug="complexity-and-asymptotic-analysis", order=3,
            summary="Estimate how runtime and memory grow with input size.",
            intuition="Big-O compares growth shape before hardware constants dominate.",
            explanation="Count dominant operations and account for nested loops, recursion trees, sorting, copying, and auxiliary structures.",
            example={"title":"Nested scan","input":"for i in range(n): for j in range(i)","output":"O(n^2)","walkthrough":"Work is 0+1+...+n-1.","code":"for i in range(n):\n    for j in range(i): work(i,j)"},
            complexity="Use O for an upper bound and Theta when tight; keep dimensions such as n and m separate.",
            guidance="Annotate loops and helpers, including library calls, sorting, copying, recursion depth, and output space.",
            traps="Multiplying independent loops, forgetting hidden costs, and treating O(n+m) as O(n).",
            practice="Rank O(n), O(n log n), O(n^2), O(2^n), and O(n!) for realistic n.",
            checkpoint="Can you justify every term from the code structure?",
            prerequisites=("problem-solving-and-cost-models","python-for-dsa"),
        ),
        _lesson(name="Invariants and Correctness", slug="invariants-and-correctness", order=4,
            summary="State what stays true while a loop or recursion advances.",
            intuition="An invariant is a proof carried by the program.",
            explanation="Show initialization, preservation, and termination; use the invariant to justify pointer moves and accumulator updates.",
            example={"title":"Running maximum","input":"[-4,-2,-9]","output":"-2","walkthrough":"After index i, best is the maximum through i.","code":"best = nums[0]\nfor value in nums[1:]: best = max(best,value)"},
            complexity="Correctness is independent of speed, but a good invariant exposes retained state and work.",
            guidance="Write the invariant, identify processed/unprocessed boundaries, then code the preserving update.",
            traps="Invalid sentinels, wrong update order, and proving only the sample.",
            practice="Write an invariant for a palindrome two-pointer check and test empty and mismatch cases.",
            checkpoint="What is true before the loop, after every iteration, and at termination?",
            prerequisites=("problem-solving-and-cost-models",),
        ),
        _lesson(name="Recursion and the Call Stack", slug="recursion-and-call-stack", order=5,
            summary="Break a problem into smaller instances with explicit base cases.",
            intuition="A recursive call promises to solve a smaller instance and combine it.",
            explanation="Define the contract, base case, progress measure, and combination step; trace frames before choosing recursion or an explicit stack.",
            example={"title":"Recursive sum","input":"[2,4,6]","output":"12","walkthrough":"First value plus suffix sum until empty returns zero.","code":"def total(nums):\n    if not nums: return 0\n    return nums[0] + total(nums[1:])"},
            complexity="A recursion tree may be linear, logarithmic, or exponential; account for stack depth and copies.",
            guidance="Write the base case first and use an index when slicing would repeatedly copy.",
            traps="Missing termination, no progress, repeated subproblems, and ignoring Python recursion depth.",
            practice="Trace factorial and tree height frame by frame, then convert one to iteration.",
            checkpoint="What does one call promise, and why does it move toward the base case?",
            prerequisites=("python-for-dsa","invariants-and-correctness"),
        ),
    ],
),
_topic(
    name="Arrays & Strings", slug="arrays-strings", display_order=2,
    description="Master ordered data, scans, grids, and text before specialized structures.",
    concepts=[
        _lesson(name="Array Fundamentals", slug="array-fundamentals", order=1,
            summary="Learn indexed storage, mutation, bounds, and the meaning of every position.",
            intuition="An array is a row of numbered boxes.",
            explanation="Use zero-based indices, distinguish values from locations, and define valid ranges before reading neighbors.",
            example={"title":"Reverse in place","input":"[1,2,3,4]","output":"[4,3,2,1]","walkthrough":"Swap outer values and move both boundaries inward.","code":"left,right=0,len(nums)-1\nwhile left<right:\n    nums[left],nums[right]=nums[right],nums[left]\n    left+=1; right-=1"},
            complexity="Index access O(1), scan O(n), in-place reversal O(1) extra space.",
            guidance="Write the range invariant and handle empty and one-element input.",
            traps="Off-by-one bounds, neighbor reads at the end, and accidental aliases.",
            practice="Trace [], [8], and [2,1,2].",
            checkpoint="Why is indexed access O(1), and what range is safe for a neighbor read?",
            prerequisites=("python-for-dsa",),
        ),
        _lesson(name="Array Traversal and Accumulators", slug="array-traversal", order=2,
            summary="Turn one scan into a correct running count, extreme, or best answer.",
            intuition="The scan boundary separates proved elements from unknown elements.",
            explanation="Choose an accumulator whose meaning stays true after every iteration; initialize from real input and define empty behavior.",
            example={"title":"Best profit","input":"[7,1,5,3,6,4]","output":"5","walkthrough":"Keep the lowest earlier price and compare the current price.","code":"lowest=prices[0]; best=0\nfor price in prices[1:]:\n    best=max(best,price-lowest); lowest=min(lowest,price)"},
            complexity="One traversal O(n); fixed state O(1); prefix arrays or sets add O(n).",
            guidance="Write what the accumulator means after index i and match update order to it.",
            traps="Zero as a maximum sentinel, future values, and mixed pre/post-update meanings.",
            practice="Trace lowest and best for [8,2,6,1,4].",
            checkpoint="Complete: after index i, the accumulator equals __ for every element through i.",
            prerequisites=("array-fundamentals","invariants-and-correctness"),
        ),
        _lesson(name="Prefix Sums and Difference Arrays", slug="prefix-sums-and-difference-arrays", order=3,
            summary="Answer repeated range totals or updates through boundary effects.",
            intuition="Subtracting two cumulative prefixes recovers the interval between them.",
            explanation="Choose an endpoint convention, derive range queries by subtraction, and mark entering/leaving boundaries for bulk updates.",
            example={"title":"Range sum","input":"[2,4,1,3], query [1,3]","output":"8","walkthrough":"With a leading zero, use prefix[4]-prefix[1].","code":"prefix=[0]\nfor value in nums: prefix.append(prefix[-1]+value)"},
            complexity="Build O(n), query O(1), difference sweep O(n+updates), space O(n).",
            guidance="Write the prefix convention and test ranges at index 0, the end, and length one.",
            traps="Mixed endpoints, missing leading zero, and missing final sweep.",
            practice="Build prefixes for [3,-1,4,2] and answer [0,2], [2,3], [1,1].",
            checkpoint="Can you derive inclusive range indices without code?",
            prerequisites=("array-traversal",),
        ),
        _lesson(name="Matrix and Grid Traversal", slug="matrix-and-grid-traversal", order=4,
            summary="Treat a grid as coordinates with explicit neighbor and boundary rules.",
            intuition="A matrix is an implicit graph: cells are nodes and directions are edges.",
            explanation="Separate row/column bounds from movement; name shrinking boundaries or visited state before spiral and flood-fill code.",
            example={"title":"Neighbors","input":"2x3 grid, cell (0,1)","output":"(1,1),(0,0),(0,2)","walkthrough":"Generate directions and retain in-bounds coordinates.","code":"for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n    nr,nc=r+dr,c+dc"},
            complexity="Full scan O(rows*cols); visited storage O(rows*cols).",
            guidance="Define coordinate order, legal neighbors, and when a cell becomes visited.",
            traps="Swapping row/column limits, revisiting cells, and mutating before reading.",
            practice="List corner neighbors on a 3x4 grid and trace a spiral boundary.",
            checkpoint="What makes a coordinate valid, and when is it visited?",
            prerequisites=("array-traversal",),
        ),
        _lesson(name="String Fundamentals and Parsing", slug="string-fundamentals-and-parsing", order=5,
            summary="Scan text, normalize deliberately, and parse tokens or nesting safely.",
            intuition="Text problems are scans plus a policy for characters and boundaries.",
            explanation="Clarify case, spaces, punctuation, and Unicode; use a builder for output and a stack for nested grammar.",
            example={"title":"Decode text","input":"3[a2[c]]","output":"accaccacc","walkthrough":"Push prior output and count at an opening bracket; combine at close.","code":"counts=[]; stack=[]; current=''; number=0\n# scan digits, brackets, and literal runs"},
            complexity="Usually O(n) plus output length; nesting stack O(n).",
            guidance="Write states and transitions, then test empty tokens, multi-digit counts, nesting, and malformed endings.",
            traps="Assuming ASCII, treating multi-digit numbers as one symbol, and accepting incomplete input.",
            practice="Draw parser state for 12[x]y and list unmatched-bracket errors.",
            checkpoint="Can you name each parser state and its transitions?",
            prerequisites=("python-for-dsa","stacks-and-queues"),
        ),
    ],
),
_topic(
    name="Hashing & Lookup", slug="hashing-lookup", display_order=3,
    description="Use maps and sets for membership, counts, pairings, and canonical keys.",
    concepts=[
        _lesson(name="Hash Maps and Sets", slug="hash-maps-and-sets", order=1,
            summary="Choose expected constant-time lookup when order is not primary.",
            intuition="A hash table turns a key into a bucket so a membership question avoids rescanning.",
            explanation="Use a set for membership and a map for key-to-value association; state each key's meaning and hash assumption.",
            example={"title":"Two sum","input":"[2,7,11,15], target 9","output":"[0,1]","walkthrough":"Query the complement before storing the current index.","code":"seen={}\nfor i,v in enumerate(nums):\n    if target-v in seen: return [seen[target-v],i]\n    seen[v]=i"},
            complexity="Expected O(n) time/O(n) space under good hashing.",
            guidance="Define the map invariant and choose query-before or query-after insertion.",
            traps="Wrong index, overwriting needed duplicates, and unqualified O(1) claims.",
            practice="Trace [3,3] target 6.",
            checkpoint="What does each map entry prove about the processed prefix?",
            prerequisites=("array-fundamentals",),
        ),
        _lesson(name="Frequency Counting", slug="frequency-counting", order=2,
            summary="Convert repeated equality checks into counts that drive decisions.",
            intuition="A count map compresses a prefix into how often each key occurred.",
            explanation="Count once, then use counts for anagrams, majority, inventory, or frequency decisions.",
            example={"title":"Anagram","input":"listen / silent","output":"True","walkthrough":"Equal character counts imply equal multisets.","code":"from collections import Counter\nreturn Counter(s)==Counter(t)"},
            complexity="O(n+m) time and O(k) space for k distinct keys.",
            guidance="Use a fixed array for a known alphabet and Counter/dict for general symbols.",
            traps="Length mismatch, unstated case policy, and mutating keys while iterating.",
            practice="Count aabcc and compare with ccaba.",
            checkpoint="What count-map condition proves the property?",
            prerequisites=("hash-maps-and-sets","string-fundamentals-and-parsing"),
        ),
        _lesson(name="Grouping and Canonicalization", slug="grouping-and-canonicalization", order=3,
            summary="Map equivalent items to stable keys so one pass can group them.",
            intuition="Equivalent inputs share a fingerprint; non-equivalent inputs must not share one under the contract.",
            explanation="Choose sorted characters, count vectors, or normalized fields that preserve exactly the intended equivalence relation.",
            example={"title":"Group anagrams","input":"eat, tea, tan, ate","output":"three plus one","walkthrough":"Sorted letters produce a shared key.","code":"groups={}\nfor word in words:\n    key=''.join(sorted(word)); groups.setdefault(key,[]).append(word)"},
            complexity="Sorted keys O(n*L log L); count-vector keys O(n*L) for fixed alphabet.",
            guidance="Write the equivalence relation before choosing the key.",
            traps="Non-hashable keys, lost order, and over-normalization.",
            practice="Design two anagram keys and compare trade-offs.",
            checkpoint="Give one pair that must collide and one that must not.",
            prerequisites=("hash-maps-and-sets","string-fundamentals-and-parsing"),
        ),
        _lesson(name="Prefix and Hash Combinations", slug="prefix-and-hash-combinations", order=4,
            summary="Combine running prefix state with lookup to find subarrays.",
            intuition="Equal transformed prefixes identify an interval with the desired relation.",
            explanation="Store earliest or latest index for each prefix sum/balance and query target differences.",
            example={"title":"Longest zero-sum subarray","input":"[1,-1,3,2,-2]","output":"4","walkthrough":"Equal prefix sums enclose a zero-sum interval.","code":"first={0:-1}; prefix=best=0\nfor i,v in enumerate(nums):\n    prefix+=v\n    if prefix in first: best=max(best,i-first[prefix])\n    else: first[prefix]=i"},
            complexity="Expected O(n) time and O(n) space.",
            guidance="Write current_prefix-earlier_prefix=target and seed empty prefix at -1.",
            traps="Wrong seed, overwriting earliest longest-query index, and mixed states.",
            practice="Trace prefix states for [1,2,-3,3].",
            checkpoint="What equation connects two prefix states to the returned interval?",
            prerequisites=("prefix-sums-and-difference-arrays","hash-maps-and-sets"),
        ),
    ],
),
_topic(
    name="Two Pointers & Sliding Window", slug="two-pointers-sliding-window", display_order=4,
    description="Shrink, expand, partition, and merge ordered ranges with proof.",
    concepts=[
        _lesson(name="Two Pointers", slug="two-pointers", order=1,
            summary="Use two moving indices to shrink a structured search space.",
            intuition="Two pointers mark the remaining interval; comparison tells which side can move safely.",
            explanation="Use sorted or directional structure, and prove why the discarded side cannot contain a solution.",
            example={"title":"Two sum in a sorted array","input":"[1,2,4,6,9], target 10","output":"indices 1,4","walkthrough":"Too-small sum can only increase by moving left forward.","code":"left, right = 0, len(nums) - 1\nwhile left < right:\n    total = nums[left] + nums[right]"},
            complexity="O(n) time/O(1) extra space, excluding sort.",
            guidance="Confirm ordering, use left<right, and state the discard proof.",
            traps="Unsorted input, reused position, and wrong pointer movement.",
            practice="List every pair for [2,3,5,8,11] target 13.",
            checkpoint="Why is moving right leftward never helpful when sum is too small?",
            prerequisites=("array-traversal",),
        ),
        _lesson(name="Partitioning and Three Pointers", slug="partitioning-and-three-pointers", order=2,
            summary="Maintain less-than, equal-to, greater-than regions in one scan.",
            intuition="Three pointers define proved regions and one unknown region.",
            explanation="Use low/mid/high; after swapping from high, inspect the new mid value before advancing.",
            example={"title":"Dutch flag","input":"[2,0,2,1,1,0]","output":"[0,0,1,1,2,2]","walkthrough":"0 left, 2 right, 1 middle.","code":"low=mid=0; high=len(nums)-1\n# inspect nums[mid], swap to its region"},
            complexity="O(n) time/O(1) extra space.",
            guidance="Draw region meanings before code.",
            traps="Advancing after an uninspected swap and breaking stability unexpectedly.",
            practice="Trace boundaries on [1,2,0,2,1].",
            checkpoint="Which region is unknown and why does the loop terminate?",
            prerequisites=("two-pointers","invariants-and-correctness"),
        ),
        _lesson(name="Fixed-Size Sliding Window", slug="fixed-size-sliding-window", order=3,
            summary="Maintain an aggregate for exactly k consecutive elements.",
            intuition="Remove the outgoing value and add the incoming value.",
            explanation="Initialize the first window, evaluate, then slide with an incremental update.",
            example={"title":"Maximum average","input":"[1,12,-5,-6,50,3], k=4","output":"12.75","walkthrough":"Subtract nums[i-k] and add nums[i].","code":"window=sum(nums[:k]); best=window\nfor right in range(k,len(nums)): window += nums[right]-nums[right-k]"},
            complexity="O(n) time/O(1) extra space after initialization.",
            guidance="Write endpoints and test k=1, k=n, and invalid k.",
            traps="Wrong outgoing item, evaluating before size k, and invalid-k bugs.",
            practice="Trace sums for [2,1,5,1,3] k=3.",
            checkpoint="Which indices are inside the window at evaluation?",
            prerequisites=("array-traversal",),
        ),
        _lesson(name="Variable-Size Sliding Window", slug="variable-size-sliding-window", order=4,
            summary="Expand and contract a contiguous range while a monotonic condition holds.",
            intuition="Right explores and left repairs; each moves forward.",
            explanation="Add right, shrink until valid, and keep the best width. Prove the input condition, such as nonnegative values.",
            example={"title":"Shortest positive-sum window","input":"[2,3,1,2,4,3], target 7","output":"2","walkthrough":"Expand until valid, then shrink while valid.","code":"left=total=0; best=float('inf')\nfor right,v in enumerate(nums):\n    total+=v\n    while total>=target: best=min(best,right-left+1); total-=nums[left]; left+=1"},
            complexity="For nonnegative inputs O(n) time/O(1) space.",
            guidance="Prove shrinking monotonicity; use prefix lookup for negative values.",
            traps="Applying to negatives without proof and forgetting no-answer output.",
            practice="Trace [1,2,3,4] target 6.",
            checkpoint="What property makes earlier left boundaries unnecessary once valid?",
            prerequisites=("fixed-size-sliding-window","hash-maps-and-sets"),
        ),
    ],
),
_topic(
    name="Linear Data Structures", slug="linear-data-structures", display_order=5,
    description="Implement and select linked lists, stacks, queues, deques, and composite structures.",
    concepts=[
        _lesson(name="Linked-List Fundamentals", slug="linked-list-fundamentals", order=1,
            summary="Manipulate nodes and links without losing the remaining list.",
            intuition="Changing one arrow can detach the suffix unless it is saved first.",
            explanation="Save next before rewiring, use a dummy head for boundary cases, and draw arrows.",
            example={"title":"Reverse list","input":"1->2->3","output":"3->2->1","walkthrough":"Save next, point backward, advance references.","code":"previous=None; current=head\nwhile current:\n    following=current.next; current.next=previous\n    previous,current=current,following"},
            complexity="O(n) time/O(1) extra space.",
            guidance="Draw previous/current/following and assert suffix reachability.",
            traps="Losing suffix, returning old head, and None dereference.",
            practice="Reverse four nodes on paper.",
            checkpoint="Which pointer leads to the unprocessed suffix?",
            prerequisites=("python-for-dsa",),
        ),
        _lesson(name="Fast and Slow Pointers", slug="fast-and-slow-pointers", order=2,
            summary="Use different speeds to detect cycles or find a midpoint.",
            intuition="Fast laps slow inside a cycle and reaches the end first otherwise.",
            explanation="Choose the loop guard and speed ratio for the desired middle/cycle contract; compare identity for cycles.",
            example={"title":"Cycle detection","input":"1->2->3->2","output":"True","walkthrough":"Relative distance changes by one each round.","code":"slow=fast=head\nwhile fast and fast.next:\n    slow=slow.next; fast=fast.next.next\n    if slow is fast: return True"},
            complexity="O(n) time/O(1) extra space.",
            guidance="Decide first/second middle and guard fast.next.",
            traps="Comparing values, unsafe dereference, and off-by-one middle.",
            practice="Trace pointers on acyclic and cyclic lists.",
            checkpoint="Why must pointers meet if a cycle exists?",
            prerequisites=("linked-list-fundamentals",),
        ),
        _lesson(name="Stacks and Queues", slug="stacks-and-queues", order=3,
            summary="Use LIFO and FIFO to model nesting and arrival order.",
            intuition="A stack remembers newest unresolved work; a queue remembers oldest waiting work.",
            explanation="Use stacks for brackets/undo/DFS-like work and queues for BFS/scheduling.",
            example={"title":"Balanced brackets","input":"([])","output":"True","walkthrough":"Each close must match the most recent opener.","code":"pairs={')':'(',']':'[','}':'{'}; stack=[]\n# push openers; pop and compare closers"},
            complexity="O(n) time and O(n) worst-case space.",
            guidance="Define what one stored item means and test empty/malformed inputs.",
            traps="Using FIFO for LIFO, popping empty state, and accepting early.",
            practice="Trace {[()]} and {[(])}.",
            checkpoint="What does the top/front prove at each step?",
            prerequisites=("python-for-dsa",),
        ),
        _lesson(name="Deque and Monotonic Structures", slug="deque-and-monotonic-structures", order=4,
            summary="Keep only candidates that can still win as a window moves.",
            intuition="A newer stronger candidate dominates an older weaker candidate.",
            explanation="Expire old indices at the front and remove dominated values from the back; store indices for expiration.",
            example={"title":"Window maximum","input":"[1,3,-1,-3,5], k=3","output":"[3,3,5]","walkthrough":"Deque front is the maximum.","code":"from collections import deque\ndq=deque()\n# expire front; remove dominated back; append index"},
            complexity="Each index enters/leaves once: O(n) time/O(k) space.",
            guidance="Separate expiration from dominance and prove deletion is safe.",
            traps="Values instead of indices, wrong expiration order, wrong monotonic direction.",
            practice="Trace deque indices for [4,2,3,1] k=2.",
            checkpoint="Why can a smaller value behind a newer larger value be deleted?",
            prerequisites=("stacks-and-queues","array-traversal"),
        ),
        _lesson(name="LRU Cache Design", slug="lru-cache-design", order=5,
            summary="Combine a hash map and doubly linked list for O(1) cache operations.",
            intuition="The map finds a key; the list orders recency.",
            explanation="Use sentinel nodes, detach before moving to recent end, and evict least recent when capacity is exceeded.",
            example={"title":"Capacity two","input":"put1,put2,get1,put3","output":"2 evicted","walkthrough":"get1 makes 2 least recent.","code":"# map key->node; list least-recent <-> most-recent"},
            complexity="Expected O(1) get/put and O(capacity) space.",
            guidance="Test detach/attach helpers, then assert map/list consistency.",
            traps="Stale map entries, double links, wrong eviction, capacity zero.",
            practice="Draw map and list after a repeated-get trace.",
            checkpoint="What must be true about map, list, and node count together?",
            prerequisites=("hash-maps-and-sets","linked-list-fundamentals"),
        ),
    ],
),
_topic(
    name="Searching, Sorting & Selection", slug="searching-sorting-selection", display_order=6,
    description="Learn order-based reasoning, boundary search, and divide-and-conquer sorting.",
    concepts=[
        _lesson(name="Binary Search", slug="binary-search", order=1,
            summary="Halve a sorted search space using a monotonic comparison.",
            intuition="Sorted order lets one comparison prove half impossible.",
            explanation="Maintain a consistent closed or half-open interval and discard the impossible side.",
            example={"title":"Find target","input":"[1,3,5,7,9], target 7","output":"3","walkthrough":"Midpoint comparisons reduce the interval.","code":"left,right=0,len(nums)-1\nwhile left<=right:\n    mid=(left+right)//2"},
            complexity="O(log n) time/O(1) extra space.",
            guidance="Choose bound convention, state invariant, and test absent targets.",
            traps="Infinite loops, mixed conventions, and unsorted input.",
            practice="Trace targets 2 and 10.",
            checkpoint="What values can still be the answer before each iteration?",
            prerequisites=("array-traversal",),
        ),
        _lesson(name="Boundary Binary Search", slug="boundary-binary-search", order=2,
            summary="Find the first or last position satisfying a monotonic predicate.",
            intuition="The goal is a false/true boundary, not the first midpoint match.",
            explanation="Record a candidate and continue toward the desired boundary; use this for duplicates and insertion positions.",
            example={"title":"First occurrence","input":"[1,2,2,2,5], target 2","output":"1","walkthrough":"On equality move left.","code":"left,right=0,len(nums)\n# if nums[mid] >= target: right=mid else left=mid+1"},
            complexity="O(log n) time/O(1) space.",
            guidance="Write predicate and boundary side before coding.",
            traps="Returning first match, wrong strictness, empty-input failures.",
            practice="Derive lower and upper bounds on [1,2,2,4].",
            checkpoint="What does left represent when the loop ends?",
            prerequisites=("binary-search",),
        ),
        _lesson(name="Binary Search on the Answer", slug="binary-search-on-answer", order=3,
            summary="Search a numeric answer space when feasibility is monotonic.",
            intuition="If capacity works, every larger capacity works.",
            explanation="Choose bounds, implement feasibility, prove monotonicity, and search smallest/largest feasible value.",
            example={"title":"Ship capacity","input":"[1,2,3,1,1], days=4","output":"3","walkthrough":"Capacity three fits in four groups; lower capacities do not.","code":"def feasible(capacity):\n    # greedily count groups\n    return days <= limit"},
            complexity="O(log answer_range * feasibility_cost).",
            guidance="Prove feasibility monotonicity and test extreme bounds.",
            traps="Non-monotonic predicate and bounds excluding answer.",
            practice="Write feasibility for splitting [7,2,5,10,8] into two groups.",
            checkpoint="Why can one feasibility result eliminate an entire side?",
            prerequisites=("boundary-binary-search","invariants-and-correctness"),
        ),
        _lesson(name="Merge Sort and Inversion Count", slug="merge-sort-and-inversion-count", order=4,
            summary="Split, solve, merge, and count cross-half relationships.",
            intuition="Merging sorted halves is linear; splitting makes n log n.",
            explanation="During merge, a right value before remaining left values contributes all those cross inversions.",
            example={"title":"Merge halves","input":"left=[2,5], right=[1,3]","output":"[1,2,3,5]","walkthrough":"1 before both left values adds two inversions.","code":"# merge pointers; if right[j] < left[i], add len(left)-i"},
            complexity="O(n log n) time/O(n) auxiliary space; stable if left wins ties.",
            guidance="Separate split, recursive result, merge, and buffer behavior.",
            traps="Double counting, unstable ties, and hidden slice copies.",
            practice="Count inversions in [2,4,1,3,5].",
            checkpoint="Why can one merge comparison count many inversions?",
            prerequisites=("recursion-and-call-stack","complexity-and-asymptotic-analysis"),
        ),
        _lesson(name="Quicksort and Quickselect", slug="quicksort-and-quickselect", order=5,
            summary="Partition around a pivot to sort or select without ordering both sides.",
            intuition="Pivot rank separates smaller and larger values.",
            explanation="Partition carefully, recurse only where needed, and defend pivot choice; quickselect stops on the target side.",
            example={"title":"Kth smallest","input":"[7,2,5,1], k=2","output":"5","walkthrough":"Partition and recurse into the side containing rank 2.","code":"# partition returns pivot index; continue only on target side"},
            complexity="Expected quicksort O(n log n), quickselect O(n), worst-case O(n^2).",
            guidance="Define partition invariant and test sorted, reverse, equal, and duplicate-heavy input.",
            traps="Off-by-one, duplicate recursion, and expected/worst-case confusion.",
            practice="Partition [3,1,2,3,0] around 3.",
            checkpoint="What is proven about pivot rank after partition?",
            prerequisites=("recursion-and-call-stack","complexity-and-asymptotic-analysis"),
        ),
    ],
),
_topic(
    name="Intervals, Greedy & Heaps", slug="intervals-greedy-heaps", display_order=7,
    description="Recognize interval order, local-choice proofs, event sweeps, and priority queues.",
    concepts=[
        _lesson(name="Interval Normalization", slug="interval-normalization", order=1,
            summary="Sort and normalize ranges before reasoning about overlap or coverage.",
            intuition="Sorted starts provide a left-to-right story; the current merged interval summarizes coverage.",
            explanation="Choose endpoint semantics, sort by start/end, and merge touching or overlapping intervals.",
            example={"title":"Merge intervals","input":"[[1,3],[2,6],[8,10]]","output":"[[1,6],[8,10]]","walkthrough":"First two overlap.","code":"intervals.sort(); merged=[]\n# append disjoint or extend current end"},
            complexity="O(n log n) sorting plus O(n) scan.",
            guidance="Write overlap predicate and test touching, nested, and point intervals.",
            traps="Wrong touching policy and contained intervals.",
            practice="Normalize [[5,7],[1,4],[3,8],[9,9]].",
            checkpoint="What does the last merged interval represent?",
            prerequisites=("array-traversal",),
        ),
        _lesson(name="Greedy Choice and Proof", slug="greedy-choice-and-proof", order=2,
            summary="Recognize when a local choice can be justified globally.",
            intuition="Greedy means a choice that belongs in some optimum by proof.",
            explanation="Separate ordering from feasibility and seek exchange, cut, or stays-ahead arguments; otherwise consider DP.",
            example={"title":"Activity selection","input":"intervals","output":"maximum compatible count","walkthrough":"Earliest finish leaves most future room.","code":"for start,end in sorted(intervals,key=lambda x:x[1]):\n    if start >= last_end: choose"},
            complexity="Often O(n log n) due to sorting; proof is the central skill.",
            guidance="State rule, test adversarial cases, and write the exchange/cut argument.",
            traps="Heuristic treated as theorem and non-canonical greedy.",
            practice="Disprove largest-coin-first change making.",
            checkpoint="What proof supports the rule or what counterexample defeats it?",
            prerequisites=("interval-normalization","array-traversal"),
        ),
        _lesson(name="Priority Queues and Heaps", slug="priority-queues-and-heaps", order=3,
            summary="Repeatedly access the smallest or largest active item.",
            intuition="A heap repairs the root after updates while leaving enough order for the next choice.",
            explanation="Use min-heaps for lowest/earliest work, max-heap simulation for largest, and understand stale entries.",
            example={"title":"Kth largest","input":"[3,2,1,5,6,4], k=2","output":"5","walkthrough":"Keep a min-heap of size k.","code":"import heapq\nh=[]\nfor v in nums:\n    heapq.heappush(h,v)\n    if len(h)>k: heapq.heappop(h)"},
            complexity="Push/pop O(log n), heapify O(n), size-k scan O(n log k).",
            guidance="Name heap invariant and whether root is answer, frontier, or discard.",
            traps="Heap mistaken for sorted array, wrong polarity, too many retained items.",
            practice="Trace size-two heap for [3,1,5,2,4].",
            checkpoint="What does root guarantee and what does it not?",
            prerequisites=("array-fundamentals",),
        ),
        _lesson(name="Top-K and Streaming", slug="top-k-and-streaming", order=4,
            summary="Maintain a bounded summary as data arrives.",
            intuition="A size-k heap is a moving cutoff; worse items can be forgotten.",
            explanation="Use heap polarity for top-k and balance two heaps for a running median.",
            example={"title":"Running median","input":"[5,2,10]","output":"[5,3.5,5]","walkthrough":"Lower values in max-heap; upper in min-heap.","code":"# maintain lower and upper heaps with sizes differing by at most one"},
            complexity="Top-k O(n log k); running median O(log n) per item/O(n) space.",
            guidance="State what each structure contains and rebalance after every update.",
            traps="Wrong even median, no rebalance, and full sort under streaming constraints.",
            practice="Insert [5,15,1,3] and draw partition.",
            checkpoint="Which values are guaranteed on each side of the heap boundary?",
            prerequisites=("priority-queues-and-heaps",),
        ),
        _lesson(name="Sweep-Line Events", slug="sweep-line-events", order=5,
            summary="Turn interval starts and ends into ordered events with active state.",
            intuition="A timeline becomes discrete changes in an active set.",
            explanation="Encode events, sort ties according to endpoint semantics, update active state, and record maxima.",
            example={"title":"Meeting rooms","input":"[[0,30],[5,10],[15,20]]","output":"2","walkthrough":"Peak active count is room requirement.","code":"events=[(s,1) for s,e in meetings]+[(e,-1) for s,e in meetings]"},
            complexity="O(n log n) event sort and O(n) scan.",
            guidance="Decide whether end at t precedes start at t and encode tie-break.",
            traps="Wrong tie order and measuring before applying events.",
            practice="Compare overlap of [1,2] and [2,3] under two endpoint policies.",
            checkpoint="What does active mean after all events at a timestamp?",
            prerequisites=("interval-normalization","priority-queues-and-heaps"),
        ),
    ],
),
_topic(
    name="Trees & Tries", slug="trees-tries", display_order=8,
    description="Move from recursive tree structure to search trees, paths, and prefix indexes.",
    concepts=[
        _lesson(name="Tree Representation and Traversals", slug="tree-representation-and-traversals", order=1,
            summary="Choose preorder, inorder, postorder, or level order intentionally.",
            intuition="Traversal order is when a walk exposes a node relative to children.",
            explanation="Use preorder for root-first, inorder for sorted BST output, postorder for child-dependent work, and BFS for levels.",
            example={"title":"Inorder","input":"root [2,1,3]","output":"[1,2,3]","walkthrough":"Left, node, right.","code":"def visit(node):\n    if not node:return\n    visit(node.left); result.append(node.value); visit(node.right)"},
            complexity="O(n) time and O(h) stack, with h possibly n.",
            guidance="State output timing and test empty, skewed, and balanced trees.",
            traps="Wrong traversal, missing None guards, assumed balanced height.",
            practice="Write all four traversals for root 1 with children 2 and 3.",
            checkpoint="Why is BST inorder sorted?",
            prerequisites=("recursion-and-call-stack",),
        ),
        _lesson(name="Recursive Tree DFS", slug="recursive-tree-dfs", order=2,
            summary="Return information from subtrees and combine it at the parent.",
            intuition="A node can answer after children report the facts it needs.",
            explanation="Define dfs(node)'s return contract, handle empty trees, compute children, and combine.",
            example={"title":"Tree height","input":"root [1,2,3,4]","output":"3","walkthrough":"One plus larger child height.","code":"def height(node):\n    if not node:return 0\n    return 1+max(height(node.left),height(node.right))"},
            complexity="O(n) time and O(h) stack.",
            guidance="Write return contract before code and separate child work from parent combination.",
            traps="Wrong return meaning, edges versus nodes, balanced-height assumption.",
            practice="Define returns for node count, max path sum, and balance.",
            checkpoint="What exactly does dfs(node) promise?",
            prerequisites=("tree-representation-and-traversals",),
        ),
        _lesson(name="Binary Search Trees", slug="binary-search-trees", order=3,
            summary="Use inherited value ranges for ordered tree operations.",
            intuition="Each subtree inherits a valid range from all ancestors.",
            explanation="Search and insert by comparison; validate with lower/upper bounds rather than only immediate children.",
            example={"title":"Validate BST","input":"[5,1,7,None,None,6,8]","output":"True","walkthrough":"6 lies in inherited (5,7).","code":"def valid(node,low,high):\n    if not node:return True\n    if not low<node.value<high:return False\n    return valid(node.left,low,node.value) and valid(node.right,node.value,high)"},
            complexity="Average O(log n) if balanced, worst O(n), space O(h).",
            guidance="Decide duplicate policy and pass full ancestor range.",
            traps="Checking only children and unqualified logarithmic claims.",
            practice="Find invalid node in [5,1,7,6,8,4].",
            checkpoint="What range may each subtree contain?",
            prerequisites=("tree-representation-and-traversals","binary-search"),
        ),
        _lesson(name="Tree Paths and Ancestors", slug="tree-paths-and-ancestors", order=4,
            summary="Carry path state or return signals for depth, sums, and ancestors.",
            intuition="Path problems move information down branches and meet it on the way up.",
            explanation="Use carried state for root-to-leaf questions and returned signals for lowest common ancestor; clarify path contract.",
            example={"title":"Lowest common ancestor","input":"targets under node 2","output":"node 2","walkthrough":"Targets appear in separate branches.","code":"def lca(node,p,q):\n    if not node or node in (p,q):return node\n    left,right=lca(node.left,p,q),lca(node.right,p,q)\n    return node if left and right else left or right"},
            complexity="O(n) time/O(h) space for a general tree.",
            guidance="Define None/non-None return meaning and handle absent targets if required.",
            traps="Assuming BST order and confusing root-to-leaf with any path.",
            practice="Trace LCA when one target is ancestor.",
            checkpoint="What does each child return, and when is parent the meeting point?",
            prerequisites=("recursive-tree-dfs",),
        ),
        _lesson(name="Trie Prefix Search", slug="trie-prefix-search", order=5,
            summary="Store shared character paths for fast word and prefix queries.",
            intuition="Shared prefixes share nodes, so lookup depends on word length.",
            explanation="Each node maps characters to children and records terminal words; traverse below a prefix for suggestions.",
            example={"title":"Prefix suggestions","input":"app, apple; prefix app","output":"both","walkthrough":"Terminal state distinguishes app from apple.","code":"class Node:\n    def __init__(self): self.children={}; self.word=False"},
            complexity="Insert/search O(L), storage O(total characters).",
            guidance="Separate exact-word terminal from prefix existence and choose child representation.",
            traps="Every prefix treated as a word, missing terminal flag, full dictionary scan.",
            practice="Insert to, tea, and ten; list shared nodes.",
            checkpoint="What differs between prefix exists and word exists?",
            prerequisites=("string-fundamentals-and-parsing","recursive-tree-dfs"),
        ),
    ],
),
_topic(
    name="Graphs & Union-Find", slug="graphs-union-find", display_order=9,
    description="Model relationships, traverse reachability, order dependencies, connect components, and optimize paths.",
    concepts=[
        _lesson(name="Graph Representation", slug="graph-representation", order=1,
            summary="Choose adjacency lists, matrices, or edge lists for the operation.",
            intuition="A graph separates entities from relationships; representation matches density and queries.",
            explanation="Use lists for sparse traversal, matrices for dense edge checks, and edge lists for sorting/relaxation; record direction and weights.",
            example={"title":"Adjacency list","input":"[(0,1),(0,2),(2,3)]","output":"neighbors","walkthrough":"Directed edges are added source to destination.","code":"graph=[[] for _ in range(n)]\nfor a,b in edges: graph[a].append(b)"},
            complexity="Lists O(V+E) space/traversal; matrices O(V^2) space.",
            guidance="Normalize input and include isolated vertices when required.",
            traps="Dropping isolated nodes, reversing direction, and dense storage for sparse graphs.",
            practice="Build directed and undirected forms for four vertices.",
            checkpoint="Which representation makes the requested operation cheapest?",
            prerequisites=("array-fundamentals",),
        ),
        _lesson(name="BFS and Unweighted Shortest Paths", slug="bfs-shortest-unweighted", order=2,
            summary="Explore layers and obtain minimum edge distance.",
            intuition="BFS exhausts paths of length d before d+1.",
            explanation="Queue a source, mark on enqueue, assign distance at first discovery, and store parents for reconstruction.",
            example={"title":"Graph path","input":"0-1,1-2,0-3,3-2","output":"distance 2","walkthrough":"Layers 0, {1,3}, then 2.","code":"from collections import deque\ndistance={source:0}; queue=deque([source])"},
            complexity="O(V+E) time/O(V) space.",
            guidance="Choose visited/distance/parent representation and mark when enqueueing.",
            traps="DFS for shortest unweighted path, late marking, disconnected target.",
            practice="Write layers and reconstruct a path.",
            checkpoint="Why can first discovery never be improved?",
            prerequisites=("graph-representation","stacks-and-queues"),
        ),
        _lesson(name="DFS Components and Topological Order", slug="dfs-components-and-topological-order", order=3,
            summary="Use depth-first state for components, cycles, and dependencies.",
            intuition="Active versus finished state exposes directed back edges.",
            explanation="Use parent checks for undirected cycles, three colors for directed cycles, and postorder or indegree removal for ordering.",
            example={"title":"Course order","input":"0->1,0->2,1->3","output":"valid order","walkthrough":"Emit zero-indegree nodes or reverse finish order.","code":"state=[0]*n\n# 0 unseen, 1 active, 2 finished"},
            complexity="O(V+E) time/O(V) space.",
            guidance="State direction and distinguish unseen, active, finished.",
            traps="Parent edge counted as cycle, reversed dependency, partial order accepted.",
            practice="Run Kahn on a graph with one cycle.",
            checkpoint="Why does an empty zero-indegree queue prove a cycle remains?",
            prerequisites=("graph-representation","recursive-tree-dfs"),
        ),
        _lesson(name="Union-Find", slug="union-find", order=4,
            summary="Maintain connected components under repeated unions and queries.",
            intuition="Each component has a representative; compression and size keep trees shallow.",
            explanation="Implement find with path compression, union by size/rank, and a component count.",
            example={"title":"Connectivity","input":"union(0,1), union(1,2)","output":"connected(0,2)=True","walkthrough":"Both resolve to the same root.","code":"def find(x):\n    if parent[x]!=x: parent[x]=find(parent[x])\n    return parent[x]"},
            complexity="Amortized near-constant operations and O(V) space.",
            guidance="Keep parent, size, and component count consistent.",
            traps="Comparing raw parents, missing compression assignment, double decrement.",
            practice="Draw unions (0,1),(2,3),(1,3) before and after compression.",
            checkpoint="When should union reduce component count?",
            prerequisites=("graph-representation",),
        ),
        _lesson(name="Dijkstra and Minimum Spanning Trees", slug="dijkstra-and-minimum-spanning-trees", order=5,
            summary="Separate shortest-path reasoning from minimum-cost connectivity.",
            intuition="Dijkstra finalizes smallest nonnegative distance; MST chooses safe cut-crossing edges.",
            explanation="Relax weighted edges with a heap for Dijkstra; use Kruskal/union-find or Prim for MST. Their objectives and proofs differ.",
            example={"title":"Weighted route","input":"0-1(4),0-2(1),2-1(2)","output":"distance 3","walkthrough":"Explore 2 then improve 1.","code":"dist[source]=0; heap=[(0,source)]\n# pop, skip stale, relax nonnegative edges"},
            complexity="Dijkstra O((V+E)logV), Kruskal O(E log E), Prim O((V+E)logV).",
            guidance="Record nonnegative precondition and distinguish cut proof from distance proof.",
            traps="Negative edge in Dijkstra, shortest tree confused with MST, cycles accepted.",
            practice="Trace stale distance 4 after improvement to 3.",
            checkpoint="What makes next Dijkstra node final and an MST edge safe?",
            prerequisites=("bfs-shortest-unweighted","priority-queues-and-heaps","union-find"),
        ),
        _lesson(name="Grid Graphs and 0-1 BFS", slug="grid-graphs-and-01bfs", order=6,
            summary="Exploit zero/one edge weights with a deque.",
            intuition="Zero-cost moves go front; one-cost moves go back, preserving distance order.",
            explanation="Generate neighbors, relax distances, and choose deque end by edge cost; use Dijkstra for arbitrary weights.",
            example={"title":"Minimum direction changes","input":"2x2 direction grid","output":"1","walkthrough":"Following arrow costs zero; changing costs one.","code":"from collections import deque\n# relax 0-cost to left and 1-cost to right"},
            complexity="O(V+E) time/O(V) space.",
            guidance="Encode move cost separately and prove deque-front minimum invariant.",
            traps="Normal BFS on weighted edges, wrong push end, no improvement check.",
            practice="Trace deque order for edge costs 0,1,1,0.",
            checkpoint="Why does the deque front contain minimum current distance?",
            prerequisites=("bfs-shortest-unweighted","dijkstra-and-minimum-spanning-trees"),
        ),
    ],
),
_topic(
    name="Recursion & Backtracking", slug="recursion-backtracking", display_order=10,
    description="Enumerate choices with reversible state and sound pruning.",
    concepts=[
        _lesson(name="Backtracking Template", slug="backtracking-template", order=1,
            summary="Choose, recurse, unchoose, and stop at complete or invalid state.",
            intuition="Backtracking walks a decision tree and cleans up before siblings.",
            explanation="Define partial state, choices, completion, and undo; copy only at a completed result.",
            example={"title":"Binary strings","input":"n=2","output":"00,01,10,11","walkthrough":"Choose each bit then pop.","code":"path=[]\ndef dfs():\n    if len(path)==n: result.append(''.join(path)); return"},
            complexity="States times work per state; output may be exponential.",
            guidance="Write state and undo first and restore shared state on every return.",
            traps="Missing undo, shared mutable path, unproven pruning.",
            practice="Draw decision tree for n=3.",
            checkpoint="What state is shared, copied, and cleaned?",
            prerequisites=("recursion-and-call-stack",),
        ),
        _lesson(name="Subsets and Permutations", slug="subsets-and-permutations", order=2,
            summary="Enumerate include/exclude choices and order-sensitive arrangements.",
            intuition="Subset chooses each item; permutation chooses an unused item for each slot.",
            explanation="Use binary branching for subsets, used flags for permutations, and sorted duplicate skipping for unique output.",
            example={"title":"Subsets","input":"[1,2]","output":"four subsets","walkthrough":"Exclude/include at each index.","code":"def dfs(i):\n    if i==len(nums): result.append(path[:]); return\n    dfs(i+1); path.append(nums[i]); dfs(i+1); path.pop()"},
            complexity="2^n subsets and n! permutations before duplicate reduction.",
            guidance="Define distinct-output semantics and choose index or used-set state.",
            traps="Reusing items, skipping valid duplicates, not copying leaf path.",
            practice="Generate unique permutations of [1,1,2].",
            checkpoint="What makes two generated outputs equal?",
            prerequisites=("backtracking-template",),
        ),
        _lesson(name="Combinations and Partitions", slug="combinations-and-partitions", order=3,
            summary="Enumerate index-ordered choices such as k-combinations and sum partitions.",
            intuition="A start index creates one canonical construction order.",
            explanation="Pass next-start, choose increasing indices, and prune on remaining slots or sum.",
            example={"title":"Choose k","input":"[1,2,3], k=2","output":"[1,2],[1,3],[2,3]","walkthrough":"Recurse from i+1.","code":"def dfs(start):\n    if len(path)==k: result.append(path[:]); return"},
            complexity="C(n,k) leaves plus path-copy work.",
            guidance="Derive a remaining-slots/sum bound before complex pruning.",
            traps="Repeated indices, over-pruning, and permutation semantics.",
            practice="List candidates for k=2 target sum 5.",
            checkpoint="Why does start=i+1 remove duplicate orderings?",
            prerequisites=("backtracking-template","subsets-and-permutations"),
        ),
        _lesson(name="Constraint Pruning", slug="constraint-pruning", order=4,
            summary="Cut branches early using bounds, feasibility, and conflict state.",
            intuition="A branch is disposable when it cannot be completed.",
            explanation="Track used columns/diagonals, remaining capacity, or lower/upper bounds; every pruning rule needs a proof.",
            example={"title":"N-Queens","input":"n=4","output":"2 solutions","walkthrough":"Reject used columns and diagonals.","code":"if col in columns or row-col in diagonals or row+col in anti: continue"},
            complexity="Worst-case exponential; sound pruning reduces explored states.",
            guidance="Name each constraint and remove exactly what was added.",
            traps="Wrong diagonal key, stale state, heuristic pruning called proof.",
            practice="Trace legal positions on first two rows.",
            checkpoint="What future possibility does each condition rule out?",
            prerequisites=("backtracking-template","subsets-and-permutations"),
        ),
    ],
),
_topic(
    name="Dynamic Programming", slug="dynamic-programming", display_order=11,
    description="Turn repeated subproblems into state, transitions, base cases, and reconstruction.",
    concepts=[
        _lesson(name="DP State and Transition", slug="dp-state-and-transition", order=1,
            summary="Define the smallest subproblem that builds the final answer.",
            intuition="DP remembers solved subproblems so repeated branches disappear.",
            explanation="Start from recursion, name state variables, write base cases, and choose top-down or bottom-up from dependency direction.",
            example={"title":"Fibonacci","input":"n=5","output":"5","walkthrough":"Each state depends on two smaller states.","code":"memo={0:0,1:1}\ndef fib(n):\n    if n not in memo: memo[n]=fib(n-1)+fib(n-2)\n    return memo[n]"},
            complexity="State count times transition cost; Fibonacci O(n) time/O(n) space.",
            guidance="Write dp[state] means before code and verify transitions decrease or are computed.",
            traps="Missing state variable, circular transition, wrong base case.",
            practice="Define states for stairs, min-cost stairs, and robber.",
            checkpoint="Can you state one dp entry without code?",
            prerequisites=("recursion-and-call-stack","invariants-and-correctness"),
        ),
        _lesson(name="One-Dimensional and State-Machine DP", slug="one-dimensional-state-machine-dp", order=2,
            summary="Solve take/skip choices and small-mode constraints compactly.",
            intuition="The DP retains only history future decisions can use.",
            explanation="Use previous states for take/skip and mutually exclusive modes for hold/cooldown.",
            example={"title":"House robber","input":"[2,7,9,3,1]","output":"12","walkthrough":"Take current plus i-2 or skip current.","code":"prev2=prev1=0\nfor v in nums: prev2,prev1=prev1,max(prev1,prev2+v)"},
            complexity="Usually O(n) time; O(n) table or O(1) compressed state.",
            guidance="Build a full table first, list dependencies, then compress safely.",
            traps="Wrong update order and impossible states initialized to zero.",
            practice="Fill table and draw cooldown states.",
            checkpoint="Which prior states suffice for dp[i]?",
            prerequisites=("dp-state-and-transition",),
        ),
        _lesson(name="Grid DP", slug="grid-dp", order=3,
            summary="Compute path counts or costs over legal grid predecessors.",
            intuition="A cell summarizes routes arriving from predecessor cells.",
            explanation="Define movement and blocked behavior, fill dependency order, and compress rows only after checking dependencies.",
            example={"title":"Minimum path","input":"3x3 cost grid","output":"7","walkthrough":"Use cheaper top/left predecessor.","code":"for r in range(rows):\n    for c in range(cols):\n        # combine legal top/left state"},
            complexity="O(rows*cols) time and O(rows*cols) or O(cols) space.",
            guidance="Draw arrows and test borders, blocked cells, and one-cell grid.",
            traps="Unavailable predecessor, accidental diagonal moves, premature compression.",
            practice="Fill a 3x3 table and derive one-row form.",
            checkpoint="Which predecessors are legal and in what order computed?",
            prerequisites=("dp-state-and-transition","matrix-and-grid-traversal"),
        ),
        _lesson(name="Subsequence and Knapsack DP", slug="subsequence-and-knapsack-dp", order=4,
            summary="Use prefix-pair or capacity states for alignment and selection.",
            intuition="The second coordinate captures another prefix or remaining capacity.",
            explanation="Compare two prefixes for subsequences; iterate capacity backward for 0/1 items.",
            example={"title":"Subset sum","input":"[1,5,11,5], target 11","output":"True","walkthrough":"Reachable sums update once per item.","code":"reachable={0}\nfor value in nums: reachable |= {s+value for s in list(reachable) if s+value<=target}"},
            complexity="Two-string DP O(nm); 0/1 knapsack O(n*capacity), pseudo-polynomial.",
            guidance="Write item-use semantics and update direction.",
            traps="Substring versus subsequence, ascending 0/1 update, hidden numeric scale.",
            practice="Trace [2,3,7] target 7 for 0/1 and unbounded.",
            checkpoint="Why does descending capacity prevent reuse?",
            prerequisites=("dp-state-and-transition","hash-maps-and-sets"),
        ),
        _lesson(name="Interval and Tree DP", slug="interval-and-tree-dp", order=5,
            summary="Combine subintervals or child states for hierarchical structure.",
            intuition="The split point or tree node is where independent subproblems meet.",
            explanation="Interval DP expands by length and tries splits; tree DP returns states such as take/not-take.",
            example={"title":"Tree independent set","input":"edges (0,1),(0,2)","output":"2","walkthrough":"Take root excludes children; skip root takes child best.","code":"def dfs(node,parent):\n    # return (take, skip) from children"},
            complexity="Tree DP often O(n); interval DP often O(n^3) before optimization.",
            guidance="List every state and transition before nested loops.",
            traps="Double-counting intervals, missing parent direction, incompatible child states.",
            practice="Derive take/skip for four-node tree.",
            checkpoint="What independent subproblems appear after the split?",
            prerequisites=("dp-state-and-transition","recursive-tree-dfs"),
        ),
        _lesson(name="DP Optimization and Reconstruction", slug="dp-optimization-and-reconstruction", order=6,
            summary="Reduce memory safely and recover the decisions behind an optimum.",
            intuition="Optimization is dependency analysis; reconstruction keeps breadcrumbs.",
            explanation="Inspect dependencies before compression, then store parents, rerun a smaller DP, or backtrack.",
            example={"title":"Recover chosen items","input":"optimal DP table","output":"one subset","walkthrough":"Compare take/skip parents backward.","code":"# parent[state] = predecessor/action\n# backtrack from final state"},
            complexity="Memory often drops from layers*states to states; backtrack is linear.",
            guidance="Prove discarded history is unnecessary and choose deterministic tie-breaking.",
            traps="Reconstructing overwritten data, wrong reversal, treating equal optima as failure.",
            practice="Add parent pointers to a small knapsack table.",
            checkpoint="What must survive the forward pass for the requested output?",
            prerequisites=("one-dimensional-state-machine-dp","subsequence-and-knapsack-dp"),
        ),
    ],
),
_topic(
    name="Advanced Interview Patterns", slug="advanced-interview-patterns", display_order=12,
    description="Use after the core loop is reliable; these are valuable but more specialized.",
    concepts=[
        _lesson(name="Divide and Conquer", slug="divide-and-conquer", order=1,
            summary="Split independent subproblems, solve them, and combine answers.",
            intuition="A recurrence exposes both the algorithm and its cost.",
            explanation="Define split, recursive contract, combine work, and prove the chosen side retains a valid answer.",
            example={"title":"Peak finding","input":"[1,3,2,4,5,1]","output":"a peak","walkthrough":"A midpoint comparison chooses a side containing a peak.","code":"mid=(left+right)//2\nif nums[mid]<nums[mid+1]: left=mid+1\nelse: right=mid"},
            complexity="Use T(n)=aT(n/b)+f(n); binary peak O(log n), merge sort O(n log n).",
            guidance="Account for split, recursive, combine, and stack work.",
            traps="Overlapping work, lost split elements, guessed recurrence.",
            practice="Write recurrences for merge sort and half-size calls plus O(n) combine.",
            checkpoint="What makes subproblems independent?",
            prerequisites=("recursion-and-call-stack",),
        ),
        _lesson(name="Bit Manipulation and Modular Math", slug="bit-manipulation-modular-math", order=2,
            summary="Use masks, parity, XOR, modular laws, and fast exponentiation.",
            intuition="Bitmasks compress yes/no choices; XOR cancels pairs; squaring reuses powers.",
            explanation="Practice &,|,^, shifts, lowbit, modular reduction, gcd, and binary exponentiation with explicit integer assumptions.",
            example={"title":"Single number","input":"[4,1,2,1,2]","output":"4","walkthrough":"XOR cancels equal pairs.","code":"answer=0\nfor value in nums: answer ^= value"},
            complexity="Bit scan O(n)/O(1); binary exponentiation O(log exponent).",
            guidance="Use truth tables and small binary examples before relying on a trick.",
            traps="Python unbounded integers, shift assumptions, overflow before modulo, invalid inverse.",
            practice="Predict x^x, x^0, x&(x-1), x&-x for x=12.",
            checkpoint="Why does x&(x-1) remove the lowest set bit?",
            prerequisites=("python-for-dsa","problem-solving-and-cost-models"),
        ),
        _lesson(name="Fenwick and Segment Trees", slug="fenwick-and-segment-trees", order=3,
            summary="Support dynamic range queries and point updates in logarithmic time.",
            intuition="A tree stores aggregates over selected ranges.",
            explanation="Fenwick uses lowbit jumps for prefix sums; segment trees split intervals and combine child aggregates.",
            example={"title":"Fenwick prefix","input":"values [2,1,3], prefix 2","output":"3","walkthrough":"Index jumps by its lowest set bit.","code":"while index>0:\n    total += tree[index]; index -= index & -index"},
            complexity="Point update/range query O(log n); storage O(n).",
            guidance="Use one indexing convention and write each node's represented range.",
            traps="Zero/one-based mix, wrong endpoints, non-associative aggregate.",
            practice="Draw Fenwick coverage for n=8 and query prefix 7.",
            checkpoint="Which disjoint ranges combine for one query?",
            prerequisites=("array-traversal","tree-representation-and-traversals"),
        ),
        _lesson(name="String Matching and Rolling Hash", slug="string-matching-and-rolling-hash", order=4,
            summary="Search text using prefix-function structure or rolling fingerprints.",
            intuition="A mismatch does not erase all prior matched structure.",
            explanation="Understand KMP prefix function and rolling hash; verify hashes when collisions matter.",
            example={"title":"KMP prefix table","input":"aabaaab","output":"prefix lengths","walkthrough":"Longest prefix also suffix gives fallback.","code":"pi=[0]*len(pattern); j=0\n# fall back with pi[j-1] on mismatch"},
            complexity="KMP O(n+m)/O(m); rolling hash expected near-linear with collision handling.",
            guidance="Draw prefix/suffix matches and decide whether exact verification is needed.",
            traps="Resetting to zero every mismatch and trusting one hash blindly.",
            practice="Compute prefix table for aabaaab.",
            checkpoint="Why can KMP skip without missing a match?",
            prerequisites=("string-fundamentals-and-parsing","prefix-and-hash-combinations"),
        ),
        _lesson(name="Max Flow and Bipartite Matching", slug="max-flow-bipartite-matching", order=5,
            summary="Model capacity constraints and pairings as augmenting paths.",
            intuition="An augmenting path reroutes existing flow to create new capacity.",
            explanation="Build residual forward/reverse edges, augment until no path remains, and reduce matching to unit-capacity flow.",
            example={"title":"Job assignment","input":"A->{1,2}, B->{2}","output":"matching size 2","walkthrough":"Residual rerouting lets A take 1 and B take 2.","code":"# residual graph; search augmenting paths and update reverse edges"},
            complexity="Edmonds-Karp O(VE^2); state algorithm and graph assumptions.",
            guidance="Draw reverse residual edges and test rerouting and disconnected nodes.",
            traps="Missing reverse capacity, stopping after one path, max versus max-weight confusion.",
            practice="Draw residual change after assigning A to job 2.",
            checkpoint="What option does a reverse residual edge represent?",
            prerequisites=("graph-representation","bfs-shortest-unweighted"),
        ),
    ],
),
]

def iter_concepts():
    """Yield topic and concept payloads in deterministic roadmap order."""
    for topic in ROADMAP_TOPICS:
        for concept in topic["concepts"]:
            yield topic, concept
