# Generated by Django 6.1.1 on 2026-09-03 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0005_learningstatus'),
        ('problems', '0004_problemsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('could_not_solve', "Couldn't solve"), ('solved_with_help', 'Solved with help'), ('solved_independently', 'Solved independently')], max_length=32)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('review_count', models.PositiveIntegerField(default=1)),
                ('last_reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_review', to='problems.problem')),
            ],
            options={
                'ordering': ('due_at', 'problem_id'),
            },
        ),
        migrations.CreateModel(
            name='ProblemReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('could_not_solve', "Couldn't solve"), ('solved_with_help', 'Solved with help'), ('solved_independently', 'Solved independently')], max_length=32)),
                ('previous_rating', models.CharField(blank=True, choices=[('could_not_solve', "Couldn't solve"), ('solved_with_help', 'Solved with help'), ('solved_independently', 'Solved independently')], max_length=32)),
                ('previous_interval_days', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField()),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('learning_status_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_events', to='practice.learningstatusevent')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reviews.problemreview')),
            ],
            options={
                'ordering': ('-reviewed_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='problemreview',
            index=models.Index(fields=['due_at', 'rating'], name='reviews_pro_due_at_102fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='problemreviewevent',
            index=models.Index(fields=['review_id', '-reviewed_at'], name='reviews_pro_review__c1c497_idx'),
        ),
        migrations.AddIndex(
            model_name='problemreviewevent',
            index=models.Index(fields=['rating', '-reviewed_at'], name='reviews_pro_rating_944aa2_idx'),
        ),
    ]
