# Generated by Django 6.1.1 on 2026-09-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice", "0002_practicerun"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunHistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_snapshot", models.TextField()),
                ("status", models.CharField(max_length=24)),
                ("result_summary", models.TextField()),
                ("passed_tests", models.PositiveIntegerField(default=0)),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("captured_at", models.DateTimeField(db_index=True)),
                (
                    "practice_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entry",
                        to="practice.practicerun",
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["status", "-captured_at"],
                        name="history_run_status_a80000_idx",
                    ),
                ],
            },
        ),
    ]
