# Generated by Django 6.1.1 on 2026-09-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("assertion_failure", "Assertion failure"),
                            ("runtime_error", "Runtime error"),
                            ("timeout", "Timed out"),
                            ("safety_violation", "Blocked for safety"),
                            ("no_tests", "No visible tests"),
                        ],
                        max_length=24,
                    ),
                ),
                ("passed_tests", models.PositiveIntegerField(default=0)),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_runs",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["problem", "-created_at"],
                        name="practice_pr_problem_cc5d9c_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="practice_pr_status_47f5c2_idx",
                    ),
                ],
            },
        ),
    ]
