# Generated by Django 6.1.1 on 2026-09-03 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=1)),
            ],
            options={"ordering": ("display_order", "id")},
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("summary", models.CharField(max_length=240)),
                ("intuition", models.TextField()),
                ("explanation", models.TextField()),
                ("examples", models.JSONField(default=list)),
                ("complexity_notes", models.TextField()),
                ("implementation_guidance", models.TextField()),
                ("common_traps", models.TextField()),
                ("guided_practice", models.TextField()),
                ("checkpoint", models.TextField()),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="curriculum.topic",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unlocks",
                        to="curriculum.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("topic", "order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("topic", "order"),
                        name="unique_concept_order_per_topic",
                    )
                ],
            },
        ),
    ]
