# Generated by Django 6.1.1 on 2026-09-03 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyblock",
            name="position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studyblock",
            name="routine_key",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="studyblock",
            name="week_start",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="studyblock",
            constraint=models.UniqueConstraint(
                condition=Q(week_start__isnull=False, routine_key__isnull=False),
                fields=("week_start", "routine_key"),
                name="planner_unique_weekly_block_key",
            ),
        ),
    ]
