# Generated by Django 6.1.1 on 2026-09-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_studyblock_weekly_routine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studyblock",
            options={"ordering": ("date", "position", "id")},
        ),
    ]
