# Generated by Django 6.1.1 on 2026-09-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_studyblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('last_resumed_at', models.DateTimeField()),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='planner.studyblock')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['study_block', 'status'], name='planner_wor_study_b_2a20ae_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('running', 'paused'))), fields=('study_block',), name='planner_one_active_work_session_per_block')],
            },
        ),
    ]
