# Generated by Django 6.1.1 on 2026-09-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_studyblock_assigned_concept"),
        ("problems", "0004_problemsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyBlockProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "assignment_source",
                    models.CharField(
                        choices=[
                            ("automatic", "Auto-filled"),
                            ("manual", "Selected by you"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_block_assignments",
                        to="problems.problem",
                    ),
                ),
                (
                    "study_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_assignments",
                        to="planner.studyblock",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [
                    models.Index(
                        fields=("study_block", "position"),
                        name="planner_stu_study_b_cb79f8_idx",
                    ),
                    models.Index(
                        fields=("problem", "study_block"),
                        name="planner_stu_problem_ac5cc5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("study_block", "problem"),
                        name="planner_unique_block_problem",
                    ),
                    models.UniqueConstraint(
                        fields=("study_block", "position"),
                        name="planner_unique_block_problem_position",
                    ),
                ],
            },
        ),
    ]
